config/routes.rb
Rails.application.routes.draw do
  get 'transport/index'
  post 'transport/calculate_max_nuts'

  root to: 'transport#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/transport_controller.rb
class TransportController < ApplicationController
  def index
    @results = JSON.parse params[:results] if params[:results]
  end

  def calculate_max_nuts
    return unless params[:input].present?

    @results = []
    input_lines = params[:input].split("\n")

    input_lines.each do |line|
      distance, nuts_amount, fuel_consumption, cart_capacity = NutCalculator.split_line(line)

      max_nuts = NutCalculator.calculate_max_nuts(distance, nuts_amount, fuel_consumption, cart_capacity)

      @results << [distance, nuts_amount, fuel_consumption, cart_capacity, max_nuts]
    end

    redirect_to transport_index_path(results: @results.to_json)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NutTransporter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/transport/index.html.erb
<h1>Nut Transporter</h1>
<h2>Calculate the maximum amount of nuts that can be transported to the town</h2>

<%= form_tag transport_calculate_max_nuts_path, method: :post do %>
  <p>
    <%= label_tag :input, "Input:" %><br>
    <%= text_area_tag :input, "", rows: 10, cols: 50 %>
  </p>

  <div class="actions">
    <%= submit_tag "Calculate" %>
  </div>
<% end %>

<% if @results.present? %>
  <h2>Results:</h2>
  <table>
    <thead>
      <tr>
        <th>Distance</th>
        <th>Nuts Amount</th>
        <th>Fuel Consumption</th>
        <th>Cart Capacity</th>
        <th>Max Nuts</th>
      </tr>
    </thead>
    <tbody>
      <% @results.each_with_index do |result, index| %>
        <tr <%= "class=alt-row" if index.odd? %>>
          <td><%= result[0] %></td>
          <td><%= result[1] %></td>
          <td><%= result[2] %></td>
          <td><%= result[3] %></td>
          <td><b><%= result[4] %></b></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>